security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'
        App\UserManagement\Infrastructure\Security\SecurityUser: 'auto'

    providers:
        database_users:
            id: App\UserManagement\Infrastructure\Security\DatabaseUserProvider

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            lazy: true
            provider: database_users
            form_login:
                login_path: login
                check_path: login
                enable_csrf: true
                default_target_path: home
            logout:
                path: logout
                target: home

    access_control:
        - { path: ^/login, roles: PUBLIC_ACCESS }
        - { path: ^/employee, roles: ROLE_EMPLOYEE }
        - { path: ^/customer, roles: ROLE_CUSTOMER }
        - { path: ^/, roles: IS_AUTHENTICATED_FULLY }

    role_hierarchy:
        ROLE_EMPLOYEE: [ROLE_USER]
        ROLE_CUSTOMER: [ROLE_USER]

when@test:
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4 # Lowest possible value for bcrypt
                time_cost: 3 # Lowest possible value for argon
                memory_cost: 10 # Lowest possible value for argon
