version: '3.7'

services:
  ebs:
    build:
      target: test
      context: .
      dockerfile: Dockerfile
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:${POSTGRES_VERSION:-16}-alpine
    volumes:
      - ./docker/postgres:/docker-entrypoint-initdb.d
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    environment:
      POSTGRES_MULTIPLE_DATABASES: ebsdatabase_test
      POSTGRES_PASSWORD: postgres
      TZ: "CET"
      PGTZ: "CET"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 2s
      timeout: 2s
      retries: 5
