version: '3.7'

services:
  ebs:
    container_name: easy-banking-service-ebs
    build:
      target: dev
      context: .
      dockerfile: Dockerfile
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    volumes:
      - ./:/app:rw
    environment:
      PHP_IDE_CONFIG: serverName=ebs
    depends_on:
      postgres_dev:
        condition: service_healthy

  nginx:
    image: nginx:alpine
    container_name: easy-banking-service-nginx
    ports:
      - "8080:80"
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./:/app:rw
    depends_on:
      - ebs

  postgres_dev:
    image: postgres:${POSTGRES_VERSION:-16}-alpine
    container_name: easy-banking-service-postgres-dev
    ports:
      - "54322:5432"
    volumes:
      - ./docker/postgres:/docker-entrypoint-initdb.d
      - postgres_dev_data:/var/lib/postgresql/data
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    environment:
      POSTGRES_MULTIPLE_DATABASES: ebsdatabase_dev
      POSTGRES_PASSWORD: postgres
      TZ: "CET"
      PGTZ: "CET"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 2s
      timeout: 2s
      retries: 5

volumes:
  postgres_dev_data:
